### PR TITLE
Finnp patch 1 - Handle error events correctly

### PR DESCRIPTION
**Pull request by naugtur**
@finnp I rebased your PR onto current v3 work 
I'm making minor changes and I want this to have tests too.

You should find an invite to be a collaborator in your email, which lets you work on this branch directly.

### CODE REVIEW

**Comment by naugtur** [comment]
@finnp Could you review what I changed on top of your PR and let me know if you have any concerns?

**Comment by nicksp** [comment]
@naugtur Hey, we're affected by a similar problem with unhandled error on a project, so wondering when do you plan to ship changes into `master`? We found suggested changes quite helpful and would like to see them merged into the main branch 😏 

For the time being, we forked the repo and did local changes, so we can reference `package.json` to a fork instead.

**Comment by naugtur** [comment]
I was going to release a new major version for quite a while now, but ran out of time and contributors. If you could help, it becomes more likely.
Now that request package is deprecated I need to rethink which changes to put in the new and likely last bigger release of xhr.

**Comment by nicksp** [comment]
@naugtur What kind of help do you expect. Tell me and I'll allocate time to help?

**Comment by naugtur** [comment]
@nicksp I don't have any expectations. I'm just a humble developer that happens to be involved in this project :)

If you want to help, the absolute first step is this: 
https://github.com/naugtur/xhr/issues/81

It'd allow improvements to tests and make it more certain that changes don't break anything.

With `request` being deprecated I'm not sure if dropping old IE support is such a great idea, but everything marked as v3 milestone is tracked in here and work has been started.
See more here: https://github.com/naugtur/xhr/issues/136

With 2 people involved I was hoping to get the v3 done and published in 2017, but we didn't end up getting to it.
I'd like to finish off and ship the last big version and then mark this library as done - no more features, low maintenance (same as in the last 2 years)

**Pull request merged**
