### PR TITLE
Fix empty response

### PR DESCRIPTION
**Pull request by naugtur**
Continuation of #126

TODO: figure out the right test for no response vs empty response

### CODE REVIEW

**Comment by TehShrike** [comment]
Since [response](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/response) is always either a string or an object that would be falsey if there was no response, I think the check should be either
```js
xhr.response || xhr.response === ''
```
or something like
```
typeof xhr.response !== 'undefined' && typeof xhr.response !== null
```

What do you mean by "no response vs empty response"?

**Comment by naugtur** [comment]
> What do you mean by "no response vs empty response"?
Empty response is when server responds and intentionally returns something we would consider "empty" in body. No response == no http body

It may be hard to distinguish. Comparing against undefined and null seems closest to what we should do, but I still have doubts - what if `responseType` is `json` and server returns `null` as body content? We need to return exactly that, but we'll step over to `else` and return `responseText` which is undefined or "null", I'd need to check.

I'll add some more test cases to document all edge cases I can reproduce.

**Comment by naugtur** [comment]
Ok, here's what I did:
1. implemented 
```
typeof xhr.response !== 'undefined' && typeof xhr.response !== null
```
with 
```
xhr.response != null
```
which results in the same thing

2. Added tests for all edge cases I could think of and adapted them to work in FF, Chrome and Phantom

3. Fixed one regression regarding responseText

What's left:

- Testing this branch in Safari and IEs
- Disabling/tweaking testcases that will break IE due to missing or buggy support for responseType

**Comment by naugtur** [comment]
Looking for volunteers to test this in IEs and Safari thoroughly.

**Comment by naugtur** [comment]
resolved and released in v2.4.0

**Pull request closed without merging**
