### PR TITLE
Ts typings

### PR DESCRIPTION
**Pull request by ghost**
This adds TypeScript typings for the project.

I didn't know if I should up the version or not. Also I decided to force the methods to be uppercased (so it can be a type union, but I can leave it as just string).

Any comments will be appreciated.

### CODE REVIEW

**Comment by naugtur** [comment]
I'm not really experienced with typescript, so I'm not sure how these are going to show up in the code for people. As for the merit and correctness, looks ok at first glance. 

Will do a second pass soon

**Comment by naugtur** [comment]
XhrBaseConfig.json should be marked as Boolean with no other options. Accepting body content there is an old mistake and we only kept it to avoid unnecessary semver major bump at some point. It won't be there in next version. When I finally finish it...

**Comment by ricardo-devis-agullo** [comment]
Hi, I added just a line on index.js to put it also on module.exports.default so it's easier to import via Typescript. The typings will show automatically once in a typescript editor.

You can see an example here:

Example

Not sure what do you mean XhrBaseConfig. Any field in particular?

**Comment by atdrago** [comment]
@ricardo-devis-agullo I think @naugtur is referring to [this line](https://github.com/naugtur/xhr/pull/174/files#diff-b52768974e6bc0faccb7d4b75b162c99R27), which should be:
```
json?: boolean;
```
 instead of:
```
json?: boolean | any;
```

**Comment by ricardo-devis-agullo** [comment]
Got it! Changed, then.

**Pull request merged**
